// BuildConfig.h.in - Generated by CMake
#ifndef OSGEARTH_BUILDCONFIG_H
#define OSGEARTH_BUILDCONFIG_H

// The SOVERSION will be a define here:
#define OSGEARTH_SOVERSION 134

#endif // OSGEARTH_BUILDCONFIG_H

